# Generated by Django 3.2.6 on 2021-09-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210923_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payementStatus',
            new_name='paymentStatus',
        ),
    ]
