# Generated by Django 3.2.6 on 2021-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_payementstatus_order_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Spices', 'Spices'), ('Condiments', 'Condiments')], max_length=255, null=True, verbose_name='Product Category'),
        ),
    ]
