# Generated by Django 3.2.4 on 2021-10-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='physicalStock',
            field=models.IntegerField(null=True, verbose_name='Physical Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='virtualStock',
            field=models.IntegerField(null=True, verbose_name='Virtual Stock'),
        ),
    ]
